config/routes.rb
Rewsly::Application.routes.draw do

    resources :stories

    root "stories#index"
    get '/search'             => 'stories#search'

  

end

app/models/story.rb
class Story < ActiveRecord::Base

	def self.search(search)
		if search
			find(:all, conditions: ['title LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

	def index
		@stories = Story.search(params[:search])
		@stories = Story.all
	end

	def show
		@story = Story.find(params[:id])
	end

	def new
		@story = Story.new
	end

	def create
		@story = Story.create(story_params)
		if @story.save 
			redirect_to "/stories"
		else
			render "new"
		end
	end

	def search

	end

	private 

	def story_params
		params.require(:story).permit(:title, :link, 
																	:upvotes, :category)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rewsly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stories/index.html.erb
<h1>Welcome to Rewsly!</h1>

<h3>All Stories</h3>
<ul>
	<% @stories.each do |story| %>
		<li><%= link_to story.title, story %></li>	
	<% end %>
</ul>

<h3>Stories with 4+ upvotes:</h3>
<ul>
	<% @stories.each do |story| %>
		<% if (story.upvotes).to_i >= 4 %>
			<li><%= link_to story.title, story %></li>	
		<% end %>
	<% end %>
</ul>

<h3>Stories Created Today: </h3>
<ul>
	<% @stories.each do |story| %>
		<% if story.created_at = Date.today %>
			<li><%= link_to story.title, story %></li>	
		<% end %>
	<% end %>
</ul>

<h3>Search for a movie: </h3>
	<%= form_tag stories_path, :method => 'get' do %>
	  <p>
	    <%= text_field_tag :search, params[:search] %>
	    <%= submit_tag "Search", :name => nil %>
	  </p>
	<% end %>

<%= link_to "Add new", new_story_path %>

app/views/stories/new.html.erb
<h1>Enter a new story: </h1>

<%= simple_form_for(@story) do |f| %>

	<%= f.input :title %>
	<%= f.input :link %>
	<%= f.input :upvotes, collection: 0..100 %>
	<%= f.input :category %>

	<%= f.submit "Add" %>

<% end %>

<%= link_to "Back Home", stories_path %>

app/views/stories/show.html.erb
<h1>Current viewing: <%= @story.title %></h1>
	<p>
		<ul>
			<li>Category: <%= @story.category %></li>
			<li>Upvotes: 	<%= @story.upvotes %></li>
			<li>Link: 		<%= link_to @story.link, @story.link %></li>
		</ul>
	</p>

<%= link_to "Back Home", stories_path %>